### PR TITLE
Namespace global secondary indexes with the table name

### LINKED ISSUE #32: Duplicate fields defined in multiple tables conflict when indexed
Given an `.arc` file looking something like this

```
@tables
users
  id *String
organizations
  id *String

@indexes

users
  provider_id *String
organizations
  provider_id *String
```

Causes the produced dynamo indexes to conflict causing the following error.

```
@tables create app-staging-users
@tables create app-production-users
@tables create app-staging-organizations
@tables create app-production-organizations
../node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

ValidationException: One or more parameter values were invalid: Duplicate index name: provider_id-index
    at Request.extractError (../node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (../node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (../node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (../node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (../node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (../node_modules/aws-sdk/lib/state_machine.js:14:12)
    at ../node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (../node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (../node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (../node_modules/aws-sdk/lib/sequential_executor.js:115:18)
```

### PR DESCRIPTION
**Pull request by jondavidjohn**
Fixes #32

### CODE REVIEW

File: src/create/aws/create-table-index/index.js [hunk 1]
```diff
@@ -13,11 +13,11 @@ module.exports = function _createIndex(params, callback) {
...
   parallel([
-    function _createStaging(callback) {
-      index(`${params.app}-staging-${name}`, attr, callback)
+    function _createStaging(cb) {
+      index(`${params.app}-staging-${name}`, attr, cb)
     },
-    function _createProduction(callback) {
-      index(`${params.app}-production-${name}`, attr, callback)
+    function _createProduction(cb) {
+      index(`${params.app}-production-${name}`, attr, cb)
```
Comment (jondavidjohn) [inline src/create/aws/create-table-index/index.js]: This was causing me issues running `npm run create` locally, resulting in this error

```
.../arc-workflows/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: callback is not a function
    at Response._tbl (.../arc-workflows/src/create/aws/create-table-index/_create-index.js:36:15)
    at Request.<anonymous> (.../arc-workflows/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (.../arc-workflows/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (.../arc-workflows/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (.../arc-workflows/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (.../arc-workflows/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (.../arc-workflows/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at .../arc-workflows/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (.../arc-workflows/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (.../arc-workflows/node_modules/aws-sdk/lib/request.js:685:12)
```

**Comment by brianleroux** [comment]
awesome: thx!! 🙏🍻
